### ISSUE TITLE
Code rename

### ISSUE THREAD

**Issue by hanwnz** [JLNU-CS-ORG/PersonalOnlineMall#5]
Please change the `<span class="shu">` label elements to `<span class="v_line">` or
 `<span class="VerticalLine">`.

We should keep standard the naming method. Please using K&R or Hump method. 

@GCYCLJKHG 

命名方法改一改 0 - 0. 少用**拼音**。

**Comment by hanwnz** [comment]
Code locate in the `src/components/commonComponents/homePage/homeHeader.vue` file.

**Comment by Fatal-Poison** [comment]
Ending
